services:
  database:
    image: postgres
    container_name: my_contacts_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
